### ISSUE TITLE
Auto Commit Failed

### ISSUE THREAD

**Issue by madfauzy** [mazipan/auto-commit#6]
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace

**Comment by X-Gorn** [comment]
change [this](https://github.com/mazipan/auto-commit/blob/9c5330c623ff1c6237e7100d1b4bc0c19a726a40/.github/workflows/autocommit.yml#L48) line to `ad-m/github-push-action@master`
