### ISSUE TITLE
AutoCommit Failing

### ISSUE THREAD

**Issue by bell-kevin** [mazipan/auto-commit#9]
Your autoCommit says it is failing currently. It was passing a while ago. Why is it not passing now? What happened? What changed? Can it be fixed? Will it be fixed? If yes, when will it be fixed?

**Comment by iamlucnguyen** [comment]
You can look at commit [https://github.com/mazipan/auto-commit/commit/a20aa8fc852f3f197d4da81c038231326bdd058e](a20aa8f), they changed `force-with-lease: true` to `force_with_lease: true` , then action can't run now.
Just undo this commit, it's working. Or simple, replace this `force_with_lease: true` to `force: true`

**Comment by bell-kevin** [comment]
Thank you!
